# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a15d25b227700d32ee5685c8441cc096b41ff5a30b5b60e253e96a29ca291092afa58905052d668fa98db02efc227c36d38f5c0a8bcda77d82c7c1051ac1ecab

test:
  secret_key_base: 15503fe3077da32be718b42b8891c41532cc480d78097c7ba03d5384390a1e2757f0b7a44e063c7d960ed7020f51c78f48e8a9b35da56498be19e9caa0a5a48a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
